// Generated by Haxe 4.0.0-rc.3+e3df7a448
(function ($global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var KinderState = $hxEnums["KinderState"] = { __ename__ : true, __constructs__ : ["Closed","Opening","Opened"]
	,Closed: {_hx_index:0,__enum__:"KinderState",toString:$estr}
	,Opening: {_hx_index:1,__enum__:"KinderState",toString:$estr}
	,Opened: {_hx_index:2,__enum__:"KinderState",toString:$estr}
};
var Main = function() {
	this.toyCounter = 0;
	this.addition = 0.;
	this.state = KinderState.Closed;
	this.lower_egg = { x : 12, y : 518.8};
	this.upper_egg = { x : 12, y : 76};
	this.assets = new haxe_ds_StringMap();
};
Main.__name__ = true;
Main.main = function() {
	var entry = new Main();
	window.onload = function() {
		entry.init();
		return;
	};
	entry.loadAssets();
};
Main.prototype = {
	init: function() {
		var _gthis = this;
		var canvas = window.document.createElement("canvas");
		this.context = canvas.getContext("2d",null);
		canvas.width = 640;
		canvas.height = 1024;
		canvas.id = "kinder_canvas";
		window.document.body.appendChild(canvas);
		canvas.onclick = function() {
			if(_gthis.state == KinderState.Closed) {
				_gthis.state = KinderState.Opening;
			} else if(_gthis.state == KinderState.Opened) {
				_gthis.upper_egg.y = 76;
				_gthis.lower_egg.y = 518.8;
				_gthis.state = KinderState.Closed;
				_gthis.setToy();
			}
		};
		this.loadAssets();
		this.setToy();
		window.requestAnimationFrame($bind(this,this.update));
	}
	,update: function(t) {
		this.draw(this.context);
		if(this.state == KinderState.Opening) {
			this.addition += 0.05;
			this.upper_egg.y -= this.addition * 15;
			this.lower_egg.y += this.addition * 15;
			if(this.upper_egg.y <= -442.8) {
				this.state = KinderState.Opened;
			}
		}
		window.requestAnimationFrame($bind(this,this.update));
	}
	,loadAssets: function() {
		this.loadImage("assets/shell_up.png","shell_up");
		this.loadImage("assets/shell_down.png","shell_down");
		this.loadToy("assets/penguin.png");
	}
	,loadToy: function(sourcePath) {
		this.loadImage(sourcePath,"toy_" + this.toyCounter);
		this.toyCounter++;
	}
	,setToy: function() {
		var this1 = this.assets;
		var key = "toy_" + Math.ceil(Math.random() * (this.toyCounter - 1));
		var _this = this1;
		this.toy = __map_reserved[key] != null ? _this.getReserved(key) : _this.h[key];
	}
	,loadImage: function(sourcePath,alias) {
		var image = new Image();
		image.src = sourcePath;
		var _this = this.assets;
		if(__map_reserved[alias] != null) {
			_this.setReserved(alias,image);
		} else {
			_this.h[alias] = image;
		}
	}
	,draw: function(context) {
		context.clearRect(0,0,640,1024);
		context.fillStyle = "#fff";
		context.strokeStyle = "#000";
		context.lineWidth = 2;
		context.fillRect(138 + this.upper_egg.y,472,300,80);
		context.strokeRect(138 + this.upper_egg.y,472,300,80);
		context.drawImage(this.toy,(640 - this.toy.width) / 2,(1280 - this.toy.height) / 2 - 64,this.toy.width,this.toy.height);
		var _this = this.assets;
		var tmp = __map_reserved["shell_up"] != null ? _this.getReserved("shell_up") : _this.h["shell_up"];
		var tmp1 = this.upper_egg.x;
		var tmp2 = this.upper_egg.y;
		var _this1 = this.assets;
		var tmp3 = (__map_reserved["shell_up"] != null ? _this1.getReserved("shell_up") : _this1.h["shell_up"]).width * 0.9;
		var _this2 = this.assets;
		context.drawImage(tmp,tmp1,tmp2,tmp3,(__map_reserved["shell_up"] != null ? _this2.getReserved("shell_up") : _this2.h["shell_up"]).height * 0.9);
		var _this3 = this.assets;
		var tmp4 = __map_reserved["shell_down"] != null ? _this3.getReserved("shell_down") : _this3.h["shell_down"];
		var tmp5 = this.lower_egg.x;
		var tmp6 = this.lower_egg.y;
		var _this4 = this.assets;
		var tmp7 = (__map_reserved["shell_down"] != null ? _this4.getReserved("shell_down") : _this4.h["shell_down"]).width * 0.9;
		var _this5 = this.assets;
		context.drawImage(tmp4,tmp5,tmp6,tmp7,(__map_reserved["shell_down"] != null ? _this5.getReserved("shell_down") : _this5.h["shell_down"]).height * 0.9);
	}
};
Math.__name__ = true;
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = true;
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) {
			return null;
		} else {
			return this.rh["$" + key];
		}
	}
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var n = e.__constructs__[o._hx_index];
			var con = e[n];
			if(con.__params__) {
				s += "\t";
				var tmp = n + "(";
				var _g = [];
				var _g1 = 0;
				var _g2 = con.__params__;
				while(_g1 < _g2.length) {
					var p = _g2[_g1];
					++_g1;
					_g.push(js_Boot.__string_rec(o[p],s));
				}
				return tmp + _g.join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g3 = 0;
			var _g11 = o.length;
			while(_g3 < _g11) {
				var i = _g3++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str1 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str1.length != 2) {
			str1 += ", \n";
		}
		str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str1 += "\n" + s + "}";
		return str1;
	case "string":
		return o;
	default:
		return String(o);
	}
};
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
if(typeof $global.$haxeUID == "undefined") $global.$haxeUID = 0;
String.__name__ = true;
Array.__name__ = true;
var __map_reserved = {};
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
js_Boot.__toStr = ({ }).toString;
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
